# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb7963ac1785453fb7f0dbb3fc21132a54bf482fa515bad5e34c5d3a2510445063d9b4ff233ae8123796398c8d583dfe63ded9fb8f2a945eccf7bb78d702c4fb

test:
  secret_key_base: abe752655acb7a962c7a6b857a08817598a2d9ecdca19cbd28d2365ed578124ee07dc01005b62ba5b3a3aef6cc32d4a8adba7fa2c8737853ab7c24019a6edcdb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
